package:
  name: data-exchange
  version: '0.1.6'

source:
  git_url: https://github.com/decarlof/data-exchange.git
  
build:
  number: 0

requirements:
  build:
    - python
 
  run:
    - python
    - scipy
    - pillow
    - scikit-image   
    - h5py
    - pyhdf
    - tifffile
    - edffile
    - spefile
    - olefile
    - netcdf4
    - dxfile

test:
  imports:
    - dataexchange

about:
  home: http://dataexchange.readthedocs.org
  license: BSD
  summary: 'Readers for various file formats. Part of tomopy a set of python routines for data analysis of x-ray tomography experiments'

