package:
  name: spefile
  version: '0.0.2'

source:
  git_url: https://github.com/decarlof/spefile.git
  
build:
  number: 0

requirements:
  build:
    - python
 
  run:
    - python

about:
  home: http://tomogrid.readthedocs.org
  license: BSD
  summary: 'X-ray tomography Data Exchange'

