package:
  name: spefile
  version: '2010'

source:
  git_url: https://github.com/decarlof/conda-recipes.git
  
build:
  number: 0

requirements:
  build:
    - python
 
  run:
    - python

test:
  imports:
    - spefile

about:
  home: https://pythonhosted.org/pyspec/
  license: BSD
  summary: 'Reader for SPE files part of pyspec a set of python routines for data analysis of x-ray scattering experiments'

