package:
  name: xtomo_hdf4
  version: '0.2'

source:
  git_url: https://github.com/decarlof/conda-recipes.git
  
build:
  number: 0

requirements:
  build:
    - python
 
  run:
    - python
    - scipy
    - pillow
    - scikit-image   
    - h5py
    - pyhdf
    - tifffile
    - edffile
    - spefile
    - olefile
    - netcdf4
    - dxfile

test:
  imports:
    - xtomo_hdf4_importer
    - xtomo_hdf4_exporter

about:
  home: http://dataexchange.readthedocs.org
  license: BSD
  summary: 'Readers for various file formats. Part of tomopy a set of python routines for data analysis of x-ray tomography experiments'

