package:
  name: dxfile
  version: '0.0.15'

source:
  git_url: https://github.com/decarlof/dxfile.git
  
build:
  number: 0

requirements:
  build:
    - python
    - h5py
 
  run:
    - python
    - h5py

about:
  home: http://tomogrid.readthedocs.org
  license: BSD
  summary: 'X-ray tomography Data Exchange'

