package:
  name: dxfile
  version: '0.1'

source:
  git_url: https://github.com/decarlof/conda-recipes.git
  
build:
  number: 0

requirements:
  build:
    - python
    - h5py
 
  run:
    - python
    - h5py

test:
  imports:
    - data_exchange

about:
  home: http://dataexchange.readthedocs.org
  license: BSD
  summary: 'Reader for Data Exchange files part of tomopy a set of python routines for data analysis of x-ray tomography experiments'

