package:
  name: olefile
  version: '0.42'

source:
  git_url: https://github.com/decarlof/olefile.git
  
build:
  number: 0

requirements:
  build:
    - python
 
  run:
    - python

test:
  imports:
    - olefile

about:
  home: https://bitbucket.org/decalage/olefileio_pl/wiki/Home
  license: BSD
  summary: 'olefile is a Python package to parse, read and write Microsoft OLE2 files'

