package:
  name: edffile
  version: '1.6'

source:
  git_url: https://github.com/decarlof/conda-recipes.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy

test:
  imports:
    - EdfFile

about:
  home: http://pymca.sourceforge.net/
  license: BSD
  summary: 'Reader for EDF files part of the PyMCA X-ray Fluorescence Toolkit'

