package:
  name: tifffile
  version: 2014.08.24

source:
  git_url: https://github.com/decarlof/conda-recipes.git

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy


test:
  imports:
    - tifffile

about:
  home: http://www.lfd.uci.edu/~gohlke/
  license: BSD
  summary: 'Read and write image data from and to TIFF files'
