package:
    name: hdf4
    version: 4.2.9

source:
    git_url: https://github.com/decarlof/conda-recipes.git

build:
    number: 0

requirements:
    build:

    run:

test:
    imports:

about:
    home: http://www.hdfgroup.org/HDF4/
    license: BSD-style (http://www.hdfgroup.org/ftp/HDF/current/src/unpacked/COPYING)
